import { Category, MenuItem, Wallpaper } from '@/types';
import { Grid3x3, Heart, House, Settings } from 'lucide-react-native';



export const categories: Category[] = [
  {
    id: '1',
    title: 'Nature',
    description: 'Mountains, Forest and Landscapes',
    wallpaperCount: 4,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
  },
  {
    id: '2',
    title: 'Abstract',
    description: 'Modern Geometric and artistic designs',
    wallpaperCount: 4,
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800',
  },
  {
    id: '3',
    title: 'Urban',
    description: 'City skylines and architecture',
    wallpaperCount: 5,
    image: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800',
  },
  {
    id: '4',
    title: 'Space',
    description: 'Galaxies, planets and cosmic wonders',
    wallpaperCount: 4,
    image: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=800',
  },
  {
    id: '5',
    title: 'Minimalist',
    description: 'Clean, simple and elegant designs',
    wallpaperCount: 4,
    image: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=800',
  },
  {
    id: '6',
    title: 'Animals',
    description: 'Wildlife and adorable creatures',
    wallpaperCount: 4,
    image: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800',
  },
];

export const wallpapers: Wallpaper[] = [
  // Nature Category
  {
    id: '1',
    title: 'Mountain Peak',
    category: 'Nature',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    isFavorite: false,
    tags: ['mountain', 'snow', 'landscape'],
    description: 'Majestic snow-capped mountain peak under blue skies',
  },
  {
    id: '2',
    title: 'Forest Path',
    category: 'Nature',
    image: 'https://images.unsplash.com/photo-1511593358241-7eea1f3c84e5?w=800',
    isFavorite: true,
    tags: ['forest', 'trees', 'path', 'green'],
    description: 'Serene forest pathway surrounded by lush greenery',
  },
  {
    id: '3',
    title: 'Lake Reflection',
    category: 'Nature',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800',
    isFavorite: false,
    tags: ['lake', 'reflection', 'sunset', 'water'],
    description: 'Perfect mirror reflection on a calm mountain lake',
  },
  {
    id: '4',
    title: 'Forest Mist',
    category: 'Nature',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
    isFavorite: false,
    tags: ['forest', 'fog', 'trees', 'atmosphere'],
    description: 'Mystical forest shrouded in morning mist',
  },

  // Urban Category
  {
    id: '5',
    title: 'City Lights',
    category: 'Urban',
    image: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800',
    isFavorite: false,
    tags: ['city', 'night', 'lights', 'skyline'],
    description: 'Dazzling city skyline illuminated at night',
  },
  {
    id: '6',
    title: 'Urban Sunset',
    category: 'Urban',
    image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800',
    isFavorite: true,
    tags: ['city', 'sunset', 'buildings', 'sky'],
    description: 'Vibrant sunset over modern city buildings',
  },
  {
    id: '7',
    title: 'Modern Architecture',
    category: 'Urban',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
    isFavorite: false,
    tags: ['architecture', 'building', 'modern', 'glass'],
    description: 'Sleek glass and steel modern architecture',
  },
  {
    id: '8',
    title: 'Downtown Streets',
    category: 'Urban',
    image: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800',
    isFavorite: false,
    tags: ['street', 'city', 'urban', 'downtown'],
    description: 'Bustling downtown city streets',
  },
  {
    id: '9',
    title: 'Bridge View',
    category: 'Urban',
    image: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800',
    isFavorite: true,
    tags: ['bridge', 'architecture', 'city', 'night'],
    description: 'Iconic bridge structure at twilight',
  },

  // Abstract Category
  {
    id: '10',
    title: 'Geometric Patterns',
    category: 'Abstract',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800',
    isFavorite: false,
    tags: ['geometric', 'pattern', 'colorful', 'modern'],
    description: 'Vibrant geometric patterns and shapes',
  },
  {
    id: '11',
    title: 'Color Waves',
    category: 'Abstract',
    image: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=800',
    isFavorite: false,
    tags: ['waves', 'gradient', 'colorful', 'fluid'],
    description: 'Flowing waves of gradient colors',
  },
  {
    id: '12',
    title: 'Liquid Art',
    category: 'Abstract',
    image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800',
    isFavorite: true,
    tags: ['liquid', 'fluid', 'artistic', 'colorful'],
    description: 'Mesmerizing liquid art with vibrant colors',
  },
  {
    id: '13',
    title: 'Neon Glow',
    category: 'Abstract',
    image: 'https://images.unsplash.com/photo-1550859492-d5da9d8e45f3?w=800',
    isFavorite: false,
    tags: ['neon', 'glow', 'light', 'abstract'],
    description: 'Glowing neon abstract composition',
  },

  // Space Category
  {
    id: '14',
    title: 'Milky Way',
    category: 'Space',
    image: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=800',
    isFavorite: true,
    tags: ['galaxy', 'stars', 'milky way', 'night sky'],
    description: 'Stunning view of the Milky Way galaxy',
  },
  {
    id: '15',
    title: 'Nebula',
    category: 'Space',
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800',
    isFavorite: false,
    tags: ['nebula', 'space', 'cosmos', 'colorful'],
    description: 'Colorful cosmic nebula in deep space',
  },
  {
    id: '16',
    title: 'Earth from Space',
    category: 'Space',
    image: 'https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?w=800',
    isFavorite: false,
    tags: ['earth', 'planet', 'space', 'blue'],
    description: 'Beautiful view of Earth from orbit',
  },
  {
    id: '17',
    title: 'Starry Night',
    category: 'Space',
    image: 'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=800',
    isFavorite: true,
    tags: ['stars', 'night', 'astronomy', 'sky'],
    description: 'Infinite stars scattered across the night sky',
  },

  // Minimalist Category
  {
    id: '18',
    title: 'Simple Lines',
    category: 'Minimalist',
    image: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=800',
    isFavorite: false,
    tags: ['minimal', 'clean', 'simple', 'lines'],
    description: 'Clean and simple line composition',
  },
  {
    id: '19',
    title: 'White Space',
    category: 'Minimalist',
    image: 'https://images.unsplash.com/photo-1508615039623-a25605d2b022?w=800',
    isFavorite: false,
    tags: ['minimal', 'white', 'clean', 'simple'],
    description: 'Elegant white space with subtle details',
  },
  {
    id: '20',
    title: 'Minimalist Desert',
    category: 'Minimalist',
    image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800',
    isFavorite: true,
    tags: ['desert', 'minimal', 'sand', 'simple'],
    description: 'Serene minimalist desert landscape',
  },
  {
    id: '21',
    title: 'Pastel Tones',
    category: 'Minimalist',
    image: 'https://images.unsplash.com/photo-1553356084-58ef4a67b2a7?w=800',
    isFavorite: false,
    tags: ['pastel', 'soft', 'minimal', 'colors'],
    description: 'Soft pastel tones in minimalist design',
  },

  // Animals Category
  {
    id: '22',
    title: 'Lion Portrait',
    category: 'Animals',
    image: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800',
    isFavorite: true,
    tags: ['lion', 'wildlife', 'animal', 'portrait'],
    description: 'Majestic lion in stunning detail',
  },
  {
    id: '23',
    title: 'Fox in Nature',
    category: 'Animals',
    image: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800',
    isFavorite: false,
    tags: ['fox', 'wildlife', 'nature', 'cute'],
    description: 'Curious fox in its natural habitat',
  },
  {
    id: '24',
    title: 'Elephant Herd',
    category: 'Animals',
    image: 'https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=800',
    isFavorite: false,
    tags: ['elephant', 'wildlife', 'herd', 'savanna'],
    description: 'Elephant family walking across the plains',
  },
  {
    id: '25',
    title: 'Colorful Bird',
    category: 'Animals',
    image: 'https://images.unsplash.com/photo-1444464666168-49d633b86797?w=800',
    isFavorite: true,
    tags: ['bird', 'colorful', 'wildlife', 'nature'],
    description: 'Vibrant exotic bird with stunning plumage',
  },
];

export const menuItems: MenuItem[] = [
  { id: '1', label: 'home', icon: House, route: '/', },
  { id: '2', label: 'browse', icon: Grid3x3, route: '/browse' },
  { id: '3', label: 'favorites', icon: Heart, route: '/favorites' },
  { id: '4', label: 'settings', icon: Settings, route: '/settings' },
];
